export const GET_LIST = 'GET_LIST';
export const CHECK_CURRENT_PRESETS = 'CHECK_CURRENT_PRESETS';
export const GET_VISIBLE_ITEMS = 'GET_VISIBLE_ITEMS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_FILTER = 'SET_FILTER';
export const SET_CATEGORY_STATUS = 'SET_CATEGORY_STATUS';
export const SET_STATUS_FOR_ALL_ITEMS = 'SET_STATUS_FOR_ALL_ITEMS';
